# Generated by Django 4.0.4 on 2022-06-12 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0002_alter_taxa_taxa_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Protein',
        ),
        migrations.DeleteModel(
            name='Taxa',
        ),
    ]
