# Generated by Django 4.0.4 on 2022-06-16 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0004_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxa',
            options={'verbose_name_plural': 'taxon'},
        ),
    ]
