# Generated by Django 4.0.4 on 2022-06-26 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0007_protein_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protein',
            name='description',
        ),
    ]
