# Generated by Django 4.0.4 on 2022-06-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0009_alter_protein_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxa',
            name='genus',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='taxa',
            name='species',
            field=models.CharField(max_length=500),
        ),
    ]
