# Generated by Django 4.0.4 on 2022-07-01 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('protein', '0010_alter_taxa_genus_alter_taxa_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proteins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxa',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taxon', to=settings.AUTH_USER_MODEL),
        ),
    ]
