# Generated by Django 4.0.4 on 2022-07-01 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0011_protein_owner_taxa_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxa',
            name='owner',
        ),
    ]
