# Generated by Django 4.0.10 on 2023-08-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0014_alter_protein_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='sequence',
            field=models.CharField(max_length=20000),
        ),
    ]
