# Generated by Django 4.0.4 on 2022-06-22 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0005_alter_pfam_domain_description_alter_pfam_domain_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pfam',
            old_name='domain_description',
            new_name='description',
        ),
    ]
