# Generated by Django 4.0.4 on 2022-06-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0006_rename_domain_description_pfam_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
